# GitHub Pages configuration for X Algorithm Flowcharts

title: X Algorithm Flowcharts
description: Hilarious flowcharts that expose how social media algorithms manipulate your attention. Finally understand why you scroll endlessly!
baseurl: /X-Algorithm-for-Noobs
url: https://tar-ive.github.io

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Social media
twitter_username: tar_ive
github_username: Tar-ive

# SEO
author: Tar-ive
lang: en

# Exclude from processing
exclude:
  - .claude/
  - .git/
  - .github/
  - node_modules/
  - vendor/
  - scripts/
  - lrasgen/
  - images/
  - "*.json"
  - "*.js"
  - "*.sh"
  - "*.md"

# Include specific files
include:
  - _config.yml
  - docs/index.html

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Analytics (optional)
google_analytics: G-XXXXXXXXXX # Replace with your GA ID

# Social sharing
og_image: /assets/images/og-image.jpg
twitter_card: summary_large_image