graph TD
    A["You: \"Just 5 minutes before bed\""] --> B[Open X/Twitter]
    B --> C{"Algorithm detects<br/>your emotional state"}
    C -->|Sad/Anxious| D["Serves comfort content<br/>\"You're not alone\" posts"]
    C -->|Happy| E["Serves rage-bait<br/>to get you angry"]
    C -->|Bored| F["Serves controversial takes<br/>\"Hot takes you won't believe\""]

    D --> G{"Variable Reward:<br/>Will this post resonate?"}
    E --> G
    F --> G

    G -->|NOPE| H["Quick scroll<br/>\"Waste of time\""]
    G -->|MAYBE| I["Slow scroll<br/>\"Hmm, interesting\""]
    G -->|HOLY SHIT| J["Complete stop<br/>\"I MUST COMMENT\""]

    H --> K["Dopamine hit: \"Saved 2 seconds\""]
    I --> L["Dopamine hit: \"Learned something\""]
    J --> M["Dopamine hit: \"Found my people!\""]

    K --> N["\"One more won't hurt\""]
    L --> N
    M --> N

    N --> O["3 hours later<br/>\"How is it 3 AM?\""]
    O --> P["Algorithm victory dance:<br/>\"Gotcha again, human\""]