graph TD
    A["Your Work Day Plan"] --> B["\"8 hours of deep focus\""]
    B --> C{"Morning Check<br/>\"Just 5 minutes\""}
    C --> D["Algorithm:<br/>\"Target acquired\""]

    D --> E{"Productivity Sabotage Protocol"}
    E --> F["\"You have 47 notifications\""]
    E --> G["\"3 threads are blowing up\""]
    E --> H["\"Someone ratio'd your friend\""]
    E --> I["\"Viral meme you MUST see\""]

    F --> J["\"Better check these\""]
    G --> J
    H --> J
    I --> J

    J --> K["Quick 2-hour detour"]
    K --> L{"Time Distortion Field"}
    L --> M["\"That felt like 10 minutes\""]
    L --> N["Reality: 2 hours gone"]
    L --> O["Work: 0% complete"]

    O --> P{"Productivity Guilt"}
    P --> Q["\"I need to be more disciplined\""]
    Q --> R["Delete app from phone"]
    R --> S["Install website blocker"]
    S --> T["Set timer for 1 hour of work"]

    T --> U{"Algorithm Counter-Attack"}
    U --> V["\"Email you HAVE to check\""]
    U --> W["\"Important work notification\""]
    U --> X["\"Quick team message\""]

    V --> Y["\"Work-related, this is fine\""]
    W --> Y
    X --> Y

    Y --> Z["3 hours later:<br/> somehow ended up on Twitter again"]
    Z --> AA["Algorithm:<br/>\"Resistance is futile\""]

    AB["Actual Productivity Hack"] --> AC["Work in airplane mode"]
    AC --> AD["Use physical distraction methods"]
    AD --> AE["Accept that you're<br/>in a behavioral experiment"]
    AE --> AF["Productivity: 300% increase<br/>Algorithm: 0% access"]